-- Create the health_check table
CREATE TABLE public.health_check (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT health_check_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Insert an initial record
INSERT INTO public.health_check (created_at)
VALUES (NOW());

-- Enable Row Level Security
ALTER TABLE public.health_check ENABLE ROW LEVEL SECURITY;