create table public.health_check (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint health_check_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO public.health_check (created_at)
VALUES (NOW());